DROP TABLE IF EXISTS Ainesosa CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Reseptiehdotus CASCADE;
DROP TABLE IF EXISTS Drinkkiresepti CASCADE;
DROP TABLE IF EXISTS Drinkinainesosa CASCADE;
